### ISSUE TITLE
 ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct PluginState’; 

### ISSUE THREAD

**Issue by shifang99** [yalue/cuda_scheduling_examiner_mirror#17]
While making, there is error.

src/matrix_multiply.cu: In function ‘void Cleanup(void*)’:
src/matrix_multiply.cu:71:7: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct PluginState’; use assignment or value-initialization instead [-Werror=class-memaccess]
   71 |   memset(state, 0, sizeof(*state));
      |   ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/matrix_multiply.cu:26:8: note: ‘struct PluginState’ declared here
   26 | typedef struct {
      |        ^
cc1plus: all warnings being treated as errors
make: *** [Makefile:132: bin/matrix_multiply.so] Error 1

**Comment by shifang99** [comment]
after git checkout at_ecrts18_submission, I can make successfully.

**Comment by yalue** [comment]
Yes, this issue seems to be due to a CUDA API change: the type of `dim3` used to be compatible with `memset`, but it is no longer.  The older tagged version still works because it does not include `matrix_multiply.cu`.  This can likely be fixed by removing the `dim3` fields from `PluginState` in `matrix_multiply.cu`, and storing the dimensions in `int[2]` instances instead.  Unfortunately, I don't really maintain this code any more.  @JoshuaJB, thoughts?

**Comment by yalue** [comment]
Should be fixed as of commit f30b2dbe7af.
